import './globals.css'
import { Inter } from 'next/font/google'
import { Nav , Footer } from '@/components/import'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next full stack',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
